<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>

        <TargetFramework>net8.0</TargetFramework>
        <IsPackable>true</IsPackable>
        <PackageId>AutofacGodotDi</PackageId>
        <Version>1.0.9</Version>
        <Authors>fzfking</Authors>
        <Description>DI for Godot using Autofac. Includes base classes for integration and a source generator for [Inject] attribute automation.</Description>
        <PackageTags>Godot;DI;Autofac;SourceGenerator</PackageTags>
        <RepositoryUrl>https://github.com/fzfking/autofac-godot-di</RepositoryUrl>
        <PackageProjectUrl>https://github.com/fzfking/autofac-godot-di</PackageProjectUrl>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        
        <DevelopmentDependency>false</DevelopmentDependency>
        <NoPackageAnalysis>true</NoPackageAnalysis>
        <PackageOutputPath>..\NuGetPackages</PackageOutputPath>
        <RootNamespace>AutofacGodotDi</RootNamespace>
        <AssemblyName>AutofacGodotDi</AssemblyName>
        
        <Nullable>disable</Nullable>
        <LangVersion>9</LangVersion>
        <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
        <RootNamespace>AutofacGodotDi</RootNamespace>
        <AssemblyName>InjectSourceGen</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.3.4">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.3.0" />
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="4.3.0" />
    </ItemGroup>
    
    <ItemGroup>
        <None Include="..\InjectSourceGen\bin\$(Configuration)\net8.0\InjectSourceGen.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
        <None Include="README.md" Pack="true" PackagePath="\" Visible="false" Condition="Exists('README.md')"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Autofac" Version="8.3.0" GeneratePathProperty="true" />
        <PackageReference Include="GodotSharp" Version="4.4.1" GeneratePathProperty="true" />
    </ItemGroup>
    
    <ItemGroup>
        <EmbeddedResource Update="Resources.resx">
            <Generator>ResXFileCodeGenerator</Generator>
            <LastGenOutput>Resources.Designer.cs</LastGenOutput>
        </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
        <Compile Update="Resources.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Resources.resx</DependentUpon>
        </Compile>
    </ItemGroup>

</Project>